### ISSUE TITLE
Не активирован package  класса GameStore в групповом проекте

### ISSUE THREAD

**Issue by Ilya195** [Ilya195/JavaGroupProject#1]
# Описание
Если не активирован package в классах связи между ними не будет.

# Локация дефекта
https://github.com/Ilya195/JavaGroupProject/blob/0533f7357cb846be9afac57f433fcae21b119984/src/main/java/GameStore.java#L1

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Ilya195/JavaGroupProject.git) в Idea.
2. В папке src найти файл GameStore.
3. Открыть файл GameStore.
4. Перейти в верхний левый угол к строке package.
 
Ожидаемый результат:  package в строке активирован
Фактический результат: строка подчеркнута волнистой линией красного цвета

# Скриншот
![image](https://user-images.githubusercontent.com/103577989/178975047-8788937b-19f7-4f27-9664-25667df1c634.png)

# Окружение
* Операционная система: Windows 7 Ultimate(64 - x)
*  IDE Intellig IDEA 2022.1.1 (Community Edition)
*  Java OpenJDK 11

**Comment by SergKry** [comment]
### Решение
commit *b69ed47* в ветке gamestore
