### ISSUE TITLE
Не корректный выбор метода в функции public void installGame(Game game) класс Prayer

### ISSUE THREAD

**Issue by SergKry** [Ilya195/JavaGroupProject#10]
## Локация дефекта 
https://github.com/Ilya195/JavaGroupProject/blob/0533f7357cb846be9afac57f433fcae21b119984/src/main/java/Player.java#L25

## Шаги воспроизведения

1.Открыть [код программы](https://github.com/Ilya195/JavaGroupProject.git) в Idea.
2.Изменить ветку репозитория на player
3. Открыть папку src
4. Открыть папку main
5. Открыть папку java
6. Открыть файл "Player"
8. Найти функцию public void installGame
9. Проверить выполнение функции public void installGame

*Ожидаемый результат:* игра приняла в себя все записанные значения
*Фактический результат:* значение в игре перезаписалось

## Скриншот

![image](https://user-images.githubusercontent.com/103843745/180296286-0441b840-e383-485c-9c04-4db4e030a4ae.png)

## Окружение
* **Операционная система:** Windows 10 Домашняя
*  IDE:Intellig IDEA 2022.1.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ilya195** [comment]
Выбор метода исправлен.
