### ISSUE TITLE
Не полное написание  функции public int play в классе "Player" отсутствует суммирование часов по жанрам

### ISSUE THREAD

**Issue by SergKry** [Ilya195/JavaGroupProject#11]
## Локация дефекта 
https://github.com/Ilya195/JavaGroupProject/blob/0533f7357cb846be9afac57f433fcae21b119984/src/main/java/Player.java#L36

## Шаги воспроизведения

1.Открыть [код программы](https://github.com/Ilya195/JavaGroupProject.git) в Idea.
2.Изменить ветку репозитория на player
3. Открыть папку src
4. Открыть папку main
5. Открыть папку java
6. Открыть файл "Player"
8. Найти функцию public int play
9. Проверить функцию public int play

*Ожидаемый результат:* игра приняла в себя все записанные значения времени и просуммировала их по жанрам
*Фактический результат:* суммирование проигранного времени не произошло

## Скриншот

![image](https://user-images.githubusercontent.com/103843745/180299431-5e8c726c-3c22-4f05-a252-445a8c358430.png)

## Окружение
* **Операционная система:** Windows 10 Домашняя
*  IDE:Intellig IDEA 2022.1.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ilya195** [comment]
Добавлено условие суммирования часов в метод Play класса Player.
