### ISSUE TITLE
Отсуствует созданный класс NotGameCatalog для выполнения метода RuntimeException

### ISSUE THREAD

**Issue by SergKry** [Ilya195/JavaGroupProject#12]
## Локация дефекта 
https://github.com/Ilya195/JavaGroupProject/tree/0533f7357cb846be9afac57f433fcae21b119984/src/main/java

## Шаги воспроизведения

1.Открыть [код программы](https://github.com/Ilya195/JavaGroupProject.git) в Idea.
2.Изменить ветку репозитория на player
3. Открыть папку src
4. Открыть папку main
5. Открыть папку java

*Ожидаемый результат: Наличие класса NotGameCatalog в папке main
*Фактический результат:* Класс NotGameCatalog отсуствует

## Скриншот

![image](https://user-images.githubusercontent.com/103843745/180300893-651cde07-49b3-4a14-901a-5908d698ae15.png)

## Окружение
* **Операционная система:** Windows 10 Домашняя
*  IDE:Intellig IDEA 2022.1.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ilya195** [comment]
## класс NotGameCatalog создан.
