### ISSUE TITLE
Не полное написание функции public int play в классе "Player" отсутствует метод выполнения условия RuntimeException при попытке проиграть не добавленную игру

### ISSUE THREAD

**Issue by SergKry** [Ilya195/JavaGroupProject#13]
## Локация дефекта 
https://github.com/Ilya195/JavaGroupProject/blob/0533f7357cb846be9afac57f433fcae21b119984/src/main/java/Player.java#L38

## Шаги воспроизведения

1.Открыть [код программы](https://github.com/Ilya195/JavaGroupProject.git) в Idea.
2.Изменить ветку репозитория на player
3. Открыть папку src
4. Открыть папку main
5. Открыть папку java
6. Открыть файл "Player"
8. Найти функцию public int play
9. Проверить функцию public int play

*Ожидаемый результат:* функция выдает ошибку "Игра '" + название игры+ "' отсутствует в вашем каталоге"
*Фактический результат:* выполнение теста падает

## Скриншот

![image](https://user-images.githubusercontent.com/103843745/180301617-46a1cfb8-50a8-4402-90c4-a938cc607130.png)

## Окружение
* **Операционная система:** Windows 10 Домашняя
*  IDE:Intellig IDEA 2022.1.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ilya195** [comment]
Добавлено исключение RuntimeException в метод Play.
