### ISSUE TITLE
Не полное написание функции public Game mostPlayerByGenre отсутствует метод для сравнения игр в рамках жанра

### ISSUE THREAD

**Issue by SergKry** [Ilya195/JavaGroupProject#14]
## Локация дефекта 
https://github.com/Ilya195/JavaGroupProject/blob/0533f7357cb846be9afac57f433fcae21b119984/src/main/java/Player.java#L59-L60
## Шаги воспроизведения

1.Открыть [код программы](https://github.com/Ilya195/JavaGroupProject.git) в Idea.
2.Изменить ветку репозитория на player
3. Открыть папку src
4. Открыть папку main
5. Открыть папку java
6. Открыть файл "Player"
8. Найти функцию public Game mostPlayerByGenre
9. Проверить функцию public Game mostPlayerByGenre

*Ожидаемый результат:* Метод принимает жанр и возвращает игру этого жанра, в которую играли больше всего
*Фактический результат:* метод возвращает только null

## Скриншот

![image](https://user-images.githubusercontent.com/103843745/180304189-7e28ecc3-0aa4-4fbd-a0aa-45852057ac52.png)

## Окружение
* **Операционная система:** Windows 10 Домашняя
*  IDE:Intellig IDEA 2022.1.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ilya195** [comment]
Добавлено описание метода mostPlayerByGenre.
