### ISSUE TITLE
класс PlayerTest не включен в необходимый package

### ISSUE THREAD

**Issue by SergKry** [Ilya195/JavaGroupProject#15]
## Описание
Класс PlayerTest не включен в необходимый package, код package не дописан.

## Локация дефекта 
https://github.com/Ilya195/JavaGroupProject/blob/0533f7357cb846be9afac57f433fcae21b119984/src/main/java/Player.java#L59-L60

## Шаги воспроизведения

1.Открыть [код программы](https://github.com/Ilya195/JavaGroupProject.git) в Idea.
2.Изменить ветку репозитория на player
3. Открыть папку src
4. Открыть папку test
5. Открыть папку java
6.Открыть файл "PlayerTest"
7.Перейти  к первой строке кода package ru.netology;

*Ожидаемый результат:* package в строке указан полностью
*Фактический результат:* Java подчеркивает ошибку кода  package

## Скриншот
![image](https://user-images.githubusercontent.com/103843745/180273580-87b4f8b7-c636-424f-8ef6-95c83ce115e7.png)

## Окружение
* **Операционная система:** Windows 10 Домашняя
*  IDE:Intellig IDEA 2022.1.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ilya195** [comment]
## Класс PlayerTest добавлен в package.
