### ISSUE TITLE
в классе Player отсутствуют Setter и Gettet на Map<Game, Integer> playedTime

### ISSUE THREAD

**Issue by SergKry** [Ilya195/JavaGroupProject#16]
## Описание
Класс PlayerTest не включен в необходимый package, код package не дописан.

## Локация дефекта 
https://github.com/Ilya195/JavaGroupProject/blob/0533f7357cb846be9afac57f433fcae21b119984/src/main/java/Player.java#L59-L60

## Шаги воспроизведения

1.Открыть [код программы](https://github.com/Ilya195/JavaGroupProject.git) в Idea.
2.Изменить ветку репозитория на player
3. Открыть папку src
4. Открыть папку main
6. Открыть папку java
7.Открыть файл "Player"
8. Найти Set and Get на Map<Game, Integer> playedTime

*Ожидаемый результат:* Set and Get на Map<Game, Integer> playedTime присутствуют в классе
*Фактический результат:* Set and Get на Map<Game, Integer> playedTime отсутствуют в классе

https://github.com/Ilya195/JavaGroupProject/blob/0533f7357cb846be9afac57f433fcae21b119984/src/main/java/Player.java#L59-L60

## Окружение
* **Операционная система:** Windows 10 Домашняя
*  IDE:Intellig IDEA 2022.1.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ilya195** [comment]
## Добавлены Getter's and Setter's.
