### ISSUE TITLE
Класс Game не импортирован в  классы проекта

### ISSUE THREAD

**Issue by SergKry** [Ilya195/JavaGroupProject#18]
## Описание
Класс Game не импортирован в  классы проекта

## Локация дефекта 
https://github.com/Ilya195/JavaGroupProject/blob/3e039287b30a48622bcd1dba51d52fb9e2c34625/src/main/java/Game.java#L1

## Описание
Класс Player не включен в необходимый package, код  не дописан.

## Локация дефекта 
https://github.com/Ilya195/JavaGroupProject/blob/3e039287b30a48622bcd1dba51d52fb9e2c34625/src/main/java/Player.java#L1

## Шаги воспроизведения

1.Открыть [код программы](https://github.com/Ilya195/JavaGroupProject.git) в Idea.
2.Изменить ветку репозитория на player
3. Открыть папку src
5. Открыть папку main
6. Открыть папку java
7.Открыть файл "Game"
8. проверить 1 строку с кодом пакета

*Ожидаемый результат:* класс Game  включен в необходимый package package ru.netology.Game и импортирован в классы
*Фактический результат:* Java подчеркивает ошибку коде пакета

## Скриншот
![image](https://user-images.githubusercontent.com/103843745/180315062-9013b60c-0104-47ad-97a3-56c672c53212.png)

## Окружение
* **Операционная система:** Windows 10 Домашняя
*  IDE:Intellig IDEA 2022.1.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ilya195** [comment]
## Класс Game импортирован.
