### ISSUE TITLE
В классе Game отсутствует необходимый package

### ISSUE THREAD

**Issue by Ilya195** [Ilya195/JavaGroupProject#19]
## Описание
Класс Game не включен в необходимый package.

## Локация дефекта 
https://github.com/Ilya195/JavaGroupProject/blob/0533f7357cb846be9afac57f433fcae21b119984/src/main/java/Game.java#L1

## Шаги воспроизведения

1.Открыть [код программы](https://github.com/Ilya195/JavaGroupProject.git) в Idea.
2. .Открыть папку src.
3. Открыть файл "Game".
4. Дописать недостающую команду.

*Ожидаемый результат:* для всех классов создан package.
*Фактический результат:* package не импортирован.

## Скриншот
![image](https://user-images.githubusercontent.com/103577989/180427982-d38b9b9e-69b0-48fb-81f7-95b7655d4204.png)

## Окружение
* **Операционная система:** Windows 7 Ultimate
*  IDE:Intellig IDEA 2022.1.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by SergKry** [comment]
### Решение
commit  *501144e* в ветке gamestore
