### ISSUE TITLE
В методе publishGame при создании обьекта Game скобках не дописано значение каталога Store 

### ISSUE THREAD

**Issue by Ilya195** [Ilya195/JavaGroupProject#2]
# Описание
Отсутствует значение каталога Store в скобках обьекта.

# Локация дефекта
https://github.com/Ilya195/JavaGroupProject/blob/0533f7357cb846be9afac57f433fcae21b119984/src/main/java/GameStore.java#L23

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/Ilya195/JavaGroupProject.git) в IDEA.
2. Найти в папке src файл GameStore.
3.  Открыть файл GameStore.
4. Обратить внимание на обьект в методе publishGame.

Ожидаемый результат: в скобках обьекта Game прописаны все переменные данного обьекта.
Фактический результат: в скобках обьекта Game написаны переменные title и genre.

# Скриншот
![image](https://user-images.githubusercontent.com/103577989/178993316-88b02bc0-e83d-453f-aba5-f846be771f20.png)

# Окружение
* Операционная система: Windows 7 Ultimate(64 - x)
* IDE Intellig IDEA 2022.1.1 (Community Edition)
* Java OpenJDK 11

**Comment by SergKry** [comment]
### Решение
commit a51429b в ветке gamestore
