### ISSUE TITLE
В классе Game некорректный синтаксис использования языка Java

### ISSUE THREAD

**Issue by Ilya195** [Ilya195/JavaGroupProject#20]
## Локация дефекта 
https://github.com/Ilya195/JavaGroupProject/blob/0533f7357cb846be9afac57f433fcae21b119984/src/main/java/Game.java#L38-L39

## Шаги воспроизведения

1.Открыть [код программы](https://github.com/Ilya195/JavaGroupProject.git) в Idea.
2.Изменить ветку репозитория на GameStore
3. Открыть папку src
4. Открыть папку test
5. Открыть папку java
6. Открыть файл "Game"

*Ожидаемый результат:* синтаксис исправлен не имеется ошибочных подчеркиваний.
*Фактический результат:*  неккоректный синтаксис класса с красным подчеркиванием.

## Скриншот
![image](https://user-images.githubusercontent.com/103577989/180601130-d1c3fc7d-c0a6-4be4-a15f-ac3d75da91ad.png)

## Окружение
* **Операционная система:** Windows 7 Ultimate
*  IDE:Intellig IDEA 2022.1.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by SergKry** [comment]
# Решение
commit *58607b6*  в ветке gamestor
