### ISSUE TITLE
Ошибка в написании в счетчике for и if в методе containsGame класса GameStore 

### ISSUE THREAD

**Issue by Ilya195** [Ilya195/JavaGroupProject#3]
# Описание
Неправильное описание в теле метода containsGame в строках for.

# Локация дефекта
https://github.com/Ilya195/JavaGroupProject/blob/0533f7357cb846be9afac57f433fcae21b119984/src/main/java/GameStore.java#L33

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Ilya195/JavaGroupProject.git) в IDEA.
2. Открыть класс GameStore.
3. Найти метод containsGame.

Ожидаемый результат: отчет счетчика должен начинаться с нуля. В get должно быть значение i.
Фактический результат: отчет счетчика начинается с единицы. В get значение i - 1.

# Скриншот
![image](https://user-images.githubusercontent.com/103577989/180226181-d773e13c-9cb9-46e6-a0e8-49a441cbc32c.png)

# Окружение
* Операционная система: Windows 7 Ultimate(64 - x)
* IDE Intellig IDEA 2022.1.1 (Community Edition)
* Java OpenJDK 11

**Comment by SergKry** [comment]
### Решение
 Commit  *578f55f*  в ветке gamestore
