### ISSUE TITLE
Наличие ошибочного цифрового значения в cтроке if метода containsGame

### ISSUE THREAD

**Issue by Ilya195** [Ilya195/JavaGroupProject#4]
# Описание
Наличие нестандартного значения в скобках строки if  метода containsGame.

# Локация дефекта
https://github.com/Ilya195/JavaGroupProject/blob/0533f7357cb846be9afac57f433fcae21b119984/src/main/java/GameStore.java#L34

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Ilya195/JavaGroupProject.git) в IDEA.
2. Открыть класс GameStore.
3. Найти метод containsGame.
4.  Перейти к строке №34

Ожидаемый результат:  В скобках games.get должно быть только значение i.
Фактический результат: В скобках games.get значение i - 1.

# Скриншот
![image](https://user-images.githubusercontent.com/103577989/180227653-e773aa6e-2e6e-4a9d-a6fe-8ce7f47978c6.png)

# Окружение
* Операционная система: Windows 7 Ultimate(64 - x)
* IDE Intellig IDEA 2022.1.1 (Community Edition)
* Java OpenJDK 11

**Comment by SergKry** [comment]
### Решение
commit *578f55f* ветка gamestore
