### ISSUE TITLE
Несоответствие фактического и ожидаемого результатов в ответе после запуска теста showGetSumOnePlayedTime  

### ISSUE THREAD

**Issue by Ilya195** [Ilya195/JavaGroupProject#5]
# Описание
Появление разницы результатов после окончания теста с отсылкой к неполному описанию метода getSumPlayedTime.

# Локация дефекта
https://github.com/Ilya195/JavaGroupProject/blob/0533f7357cb846be9afac57f433fcae21b119984/src/main/java/GameStore.java#L75-L76

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Ilya195/JavaGroupProject.git) в IDEA.
2. Открыть класс GameStore.
3. Найти метод getSumPlayedTime.
4.  Перейти к строке №75

Ожидаемый результат:  в методе getSumPlayedTime написано условие при котором проходит тест.
Фактический результат: в методе не закончено условие для успешного прохождения теста.

# Скриншот
![image](https://user-images.githubusercontent.com/103577989/180230662-efd9fca3-5989-4e29-9da1-437f872a4216.png)

# Окружение
* Операционная система: Windows 7 Ultimate(64 - x)
* IDE Intellig IDEA 2022.1.1 (Community Edition)
* Java OpenJDK 11

**Comment by SergKry** [comment]
### Решение
commit *3e03928* в ветке gamestore
