### ISSUE TITLE
Неполное описание в теле метода addPlayTime класса GameStore при котором отсутствует возможность суммировать значения

### ISSUE THREAD

**Issue by Ilya195** [Ilya195/JavaGroupProject#6]
# Описание
Отсутствие возможности суммировать прошлое значение с настоящим из-за неполного условия метода addPlayTime.

# Локация дефекта
https://github.com/Ilya195/JavaGroupProject/blob/0533f7357cb846be9afac57f433fcae21b119984/src/main/java/GameStore.java#L48

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Ilya195/JavaGroupProject.git) в IDEA.
2. Открыть класс GameStore.
3. Найти метод addPlayTime.
4.  Перейти к строке №48

Ожидаемый результат:  метод суммирует прошлое значение игровых часов(если оно есть) с настоящим.
Фактический результат: в методе нет процесса суммирования часов ни прошлых игр ни имеющихся в данный момент.

# Скриншот
![image](https://user-images.githubusercontent.com/103577989/180238900-5188b1f7-1669-48f6-bf92-f623b7976aec.png)

# Окружение
* Операционная система: Windows 7 Ultimate(64 - x)
* IDE Intellig IDEA 2022.1.1 (Community Edition)
* Java OpenJDK 11

**Comment by SergKry** [comment]
### Решение

commit *e295fd3* в ветке gamestore
