### ISSUE TITLE
в классе PlayerTest отсутствует необходимый  импорт package из класса Player

### ISSUE THREAD

**Issue by SergKry** [Ilya195/JavaGroupProject#7]
## Описание
Класс PlayerTest не включен в необходимый package, код  не дописан.

## Локация дефекта 
https://github.com/Ilya195/JavaGroupProject/blob/0533f7357cb846be9afac57f433fcae21b119984/src/test/java/PlayerTest.java#L2

## Шаги воспроизведения

1.Открыть [код программы](https://github.com/Ilya195/JavaGroupProject.git) в Idea.
2.Изменить ветку репозитория на player
3. Открыть папку src
5. Открыть папку test
6.Открыть файл "PlayerTest"
7. Создать объект типа Player

*Пример:*  Player player = new Player("Петя");

*Ожидаемый результат:* объект типа Player создан
*Фактический результат:* Java подчеркивает ошибку в объекте  типа Player

## Скриншот
![image](https://user-images.githubusercontent.com/103843745/180279013-f3e37aff-6c14-4a57-a8a0-7b3eff222cf8.png)

## Окружение
* **Операционная система:** Windows 10 Домашняя
*  IDE:Intellig IDEA 2022.1.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ilya195** [comment]
## В классе PlayerTest создан необходимый package.
