### ISSUE TITLE
в классе PlayerTest отсутствует необходимый  импорт package из класса GameStore

### ISSUE THREAD

**Issue by SergKry** [Ilya195/JavaGroupProject#8]
## Описание
Класс PlayerTest не включен в необходимый package, код  не дописан.

## Локация дефекта 
https://github.com/Ilya195/JavaGroupProject/blob/0533f7357cb846be9afac57f433fcae21b119984/src/test/java/PlayerTest.java#L2

## Шаги воспроизведения

1.Открыть [код программы](https://github.com/Ilya195/JavaGroupProject.git) в Idea.
2.Изменить ветку репозитория на player
3. Открыть папку src
5. Открыть папку test
6. Открыть папку java
7.Открыть файл "PlayerTest"
8. Создать объект типа GameStore

*Пример:* GameStore store = new GameStore();

*Ожидаемый результат:* объект типа GameStore создан
*Фактический результат:* Java подчеркивает ошибку в объекте  типа GameStore

## Скриншот
![image](https://user-images.githubusercontent.com/103843745/180277837-af849473-46d4-4955-9e1e-de61d5a4a7c5.png)

## Окружение
* **Операционная система:** Windows 10 Домашняя
*  IDE:Intellig IDEA 2022.1.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ilya195** [comment]
## В классе PlayerTest создан импорт класса GameStore.
