### ISSUE TITLE
Некорректный синтаксис использования языка Java в фунции "public boolean equals" класса Game

### ISSUE THREAD

**Issue by SergKry** [Ilya195/JavaGroupProject#9]
## Локация дефекта 
https://github.com/Ilya195/JavaGroupProject/blob/0533f7357cb846be9afac57f433fcae21b119984/src/main/java/Game.java#L29-L41

## Шаги воспроизведения

1.Открыть [код программы](https://github.com/Ilya195/JavaGroupProject.git) в Idea.
2.Изменить ветку репозитория на player
3. Открыть папку src
4. Открыть папку test
5. Открыть папку java
6. Открыть файл "PlayerTest"
8. Запустить тест :
(https://github.com/Ilya195/JavaGroupProject/blob/0533f7357cb846be9afac57f433fcae21b119984/src/test/java/PlayerTest.java#L8-L20)
*Ожидаемый результат:* тест прошел успешно и согласен, что  количество проигранных часов в рамках жанра "Аркады" равно 3 
*Фактический результат:* тест упал отсылкой к функции "public boolean equals" класса Game
## Скриншот
![image](https://user-images.githubusercontent.com/103843745/180283632-6f446a29-d936-45b0-9b06-336e99ebfb76.png)

## Окружение
* **Операционная система:** Windows 10 Домашняя
*  IDE:Intellig IDEA 2022.1.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ilya195** [comment]
## Некорректный синтаксис в классе Game исправлен.
